insert into task values(1, '2022-09-04', 'Wybrać termin wesela', 'Zrobione', '2021-01-15');
insert into task values(2, 'ok. 20-30 gości', 'Określić planowaną liczbę gości', 'Zrobione', '2021-01-27');
insert into task values(3, 'ok. 30 000 pln', 'Określić budżet na wesele', 'Zrobione', '2021-01-23');
insert into task values(4, 'Zarezerwowana', 'Wybrać salę', 'Zrobione', '2021-02-14');
insert into task values(5, 'Termin 4.09 100 pln', 'Załatwić formalności w US', 'Zrobione', '2021-02-07');
insert into task values(6, 'Poprawki krawieckie', 'Wybrać suknię ślubną', 'W trakcie', '2021-02-21');
insert into task values(7, 'Hubert i Agnieszka', 'Poprosić świadków o zgodę', 'Zrobione', '2021-02-01');
insert into task values(8, '35 szt.', 'Zamówić zaproszenia', 'Zrobione', '2021-03-02');
insert into task values(9, 'Dominika Photography', 'Wybrać fotografa', 'Zrobione', '2021-02-04');
insert into task values(10, 'Tuberoza', 'Zamówić kwiaty', 'Zrobione', '2021-04-26');
insert into task values(11, 'DJ Dr Bass', 'Wybrać orkiestrę/DJ', 'Zrobione', '2021-04-01');
insert into task values(12, 'Aclari', 'Kupić obrączki ślubne', 'W trakcie', '2021-05-08');
insert into task values(13, 'Farouk 9:30', 'Makijaż i fryzura', 'Zrobione', '2021-05-23');
insert into task values(14, 'wysłać pocztą', 'Rozdać zaproszenia', 'W trakcie', '2021-06-07');
insert into task values(15, 'Jedziemy swoją Hondą', 'Zarezerwować samochód', 'Zrobione', '2021-04-10');
insert into task values(16, 'Musimy dokupić bo wypiliśmy', 'Kupić alkohol', 'W trakcie', '2021-06-08');
insert into task values(17, 'Pakiet standard', 'Ustalić menu weselne', 'Zrobione', '2021-05-27');
insert into task values(18, 'Złoto-biały wanilia', 'Zamówić tort', 'Zrobione', '2021-05-26');
insert into task values(19, 'Kupić buty na zmianę', 'Dodatki do stroju', 'W trakcie', '2021-06-08');
insert into task values(20, 'Grecja Santorini', 'Zaplanować podróż poślubną', 'Do zrobienia', '2021-06-03');
insert into task values(21, 'Stół prostokątny', 'Ustalić usadzenie gości', 'Do zrobienia', '2021-06-03');
insert into task values(22, 'Sala i fotograf', 'Zapłacić zaliczki', 'W trakcie', '2021-06-01');
insert into task values(23, 'Spa Studio Sante', 'Wieczór panieński/kawalerski', 'Do zrobienia', '2021-08-28');
insert into task values(24, '3 dni przed ślubem', 'Odebrać suknię', 'Do zrobienia', '2021-06-01');
insert into task values(25, 'tydzień przed ślubem', 'Potwierdzić terminy z usługodawcami', 'Do zrobienia', '2021-06-01');
insert into task values(26, 'w dniu ślubu', 'Wziąć dowód osobisty', 'Do zrobienia', '2021-06-01');
insert into task values(27, ':)', 'Nie stresować się', 'Nowy', '2021-06-10');
insert into guest values(1, 'Panna młoda', 'Organizator');
insert into guest values(2, 'Pan młody', 'Organizator');
insert into guest values(3, 'Mariusz Pudzianowski', 'Zaprosić');
insert into guest values(4, 'Anna Mucha', 'Zaprosić');
insert into guest values(5, 'Robert Lewandowski', 'Zaprosić');
insert into guest values(6, 'Donald Tusk', 'Zaprosić');
insert into guest values(7, 'Dorota Rabczewska', 'Zaprosić');
insert into guest values(8, 'Tomasz Karolak', 'Niepotwierdzone');
insert into guest values(9, 'Agnieszka Radwańska', 'Potwierdzone');
insert into guest values(10, 'Julia Wieniawa', 'Zaprosić');
insert into guest values(11, 'Andrzej Piaseczny', 'Zaprosić');
insert into guest values(12, 'Weronika Rosati', 'Potwierdzone');
insert into guest values(13, 'Martyna Wojciechowska', 'Potwierdzone');
insert into guest values(14, 'Filip Chajzer', 'Potwierdzone');
insert into guest values(15, 'Aleksandra Szwed', 'Zaprosić');
insert into guest values(16, 'Tomasz Kot', 'Zaprosić');
insert into guest values(17, 'Marcin Najman', 'Zaprosić');
insert into guest values(18, 'Kamil Stoch', 'Zaprosić');
insert into guest values(19, 'Hubert Urbański', 'Potwierdzone');
insert into guest values(20, 'Rafał Trzaskowski', 'Niepotwierdzone');
insert into guest values(21, 'Ivan Komarenko', 'Zaprosić');
insert into gift values(1, 'Marcin Najman', 'Mikser', 1);
insert into gift values(2, 'Agnieszka Radwańska', 'Zestaw garnków', 1);
insert into gift values(3, 'Julia Wieniawa', 'Pralka', 1);
insert into gift values(4, 'Donald Tusk', 'Suszarka do grzybów', 1);
insert into gift values(5, 'Anna Mucha', 'Maszynka do mięsa', 1);
insert into gift values(6, 'Tomasz Karolak', 'Wózek dla dziecka', 1);
insert into gift values(7, 'Kamil Stoch', 'Sanki', 1);
insert into gift values(8, 'Dorota Rabczewska', 'Wino', 1);
insert into gift values(9, 'Rafał Trzaskowski', 'Pusta koperta', 1);
insert into gift values(10, 'Weronika Rosati', 'Pościel', 1);
insert into gift values(11, 'Hubert Urbański', 'Kolejny odkurzacz', 1);
insert into gift values(12, 'Mariusz Pudzianowski', 'Przeterminowana bombonierka', 1);
insert into gift values(13, 'Julia Wieniawa', 'Opiekacz do kanapek', 1);
insert into gift values(14, 'Aleksandra Szwed', 'Zastawa obiadowa', 1);
insert into gift values(15, 'Robert Lewandowski', 'Sztućce', 1);
insert into gift values(16, 'Filip Chajzer', 'Karma dla psa', 1);
insert into gift values(17, 'Andrzej Piaseczny', 'Dywan', 1);
insert into gift values(18, 'Robert Lewandowski', 'Kosiarka do trawy', 1);
insert into gift values(19, 'Anna Mucha', 'Maszyna do szycia', 1);
insert into gift values(20, 'Marcin Najman', 'Rower', 1);
insert into gift values(21, 'Tomasz Kot', 'Żółte róże z kolcami', 1);
insert into gift values(22, 'Martyna Wojciechowska', 'Lot balonem', 1);
insert into gift values(23, 'Rafał Trzaskowski', 'Perły', 1);
insert into gift values(24, 'Ivan Komarenko', 'Podrabiana biżuteria', 1);
insert into gift values(25, 'Tomasz Karolak', 'Tanie wino', 1);
insert into mybudget values(1, 30000);
insert into expences values(1, 'Opłata w USC', 100);
insert into expences values(2, 'Sala', 11000);
insert into expences values(3, 'Obrączki', 4000);
insert into expences values(4, 'Suknia ślubna', 3000);
insert into expences values(5, 'Garnitur', 2000);
insert into expences values(6, 'Dodatki do stroju', 1200);
insert into expences values(7, 'Kwiaty i dekoracje', 2300);
insert into expences values(8, 'Fotograf', 1600);
insert into expences values(9, 'Fryzura i makijaż', 350);
insert into expences values(10, 'Tort', 190);
insert into expences values(11, 'Alkohol', 230);
insert into expences values(12, 'DJ', 2000);
insert into users values(1,	'wierzbicka@pw.pl', 'Martyna', 'Wierzbicka', '$2a$10$lGnGIZDzABgQWQfYzlHcnOnEF.965B8CRLd5JNamEgDrVUcGOj3vm');
insert into users values(2,	'ee@ee.pl', 'Edwin', 'Piekarski', '$2a$10$lGnGIZDzABgQWQfYzlHcnOnEF.965B8CRLd5JNamEgDrVUcGOj3vm');
insert into users values(3,	'hapsia@pw.pl', 'Hapsia', 'Hapsia', '$2a$10$lGnGIZDzABgQWQfYzlHcnOnEF.965B8CRLd5JNamEgDrVUcGOj3vm');
insert into roles values(1, 'User');
insert into roles values(2, 'Admin');
insert into users_roles values (1, 2);
insert into users_roles values (2, 2);
insert into users_roles values (3, 1);